### ISSUE TITLE
Does it close everything at the installation of the addon?

### ISSUE THREAD

**Issue by cecton** [igorlogius/auto-close-tabs#3]
I'm looking for an extension to close old tabs because I have thousands. Ideally I want to keep 3 months of tabs. On some other addon I read the cleanup starts upon installation but I don't want that, I would like to get the chance to configure the thing first.

Does this extension closes everything at the installation or will I have the chance to change the settings first?

Kind regards

Related to https://github.com/qzb/dustman/issues/39

**Comment by igorlogius** [comment]
You can modify the settings. The addon is initally disabled, aka no window is monitored. 

You can include and exlucde Windows from the cleanup cylbe, simply by clicking the toolbar button. 

PS: If you have a lot of tabs i'd still suggest, you first make a manual copy of all open tab urls with maybe something like https://addons.mozilla.org/en-US/firefox/addon/copy-tabs/ or similar so in case anything goes wrong, you'll be able to recover (https://addons.mozilla.org/en-US/firefox/addon/open-tabs-from-file-or-clip/ )

Hope this info helps.

**Comment by cecton** [comment]
> If you have a lot of tabs i'd suggest, you make a manual copy of all open tab urls with maybe something like [addons.mozilla.org/en-US/firefox/addon/copy-tabs](https://addons.mozilla.org/en-US/firefox/addon/copy-tabs/) so in case anything goes wrong, you'll be able to recover ([addons.mozilla.org/en-US/firefox/addon/open-tabs-from-file-or-clip](https://addons.mozilla.org/en-US/firefox/addon/open-tabs-from-file-or-clip/) )

Thanks A LOT for the tip!

I just saved them. Not for future readers: by default it copies tab's title xD not very useful. You have to change in the settings to "Copy all tabs as Text URLs". Also: it works per window basis.

god I have 1212 tabs on 1 window and 842 on the other :joy:

**Comment by cecton** [comment]
oh wow it can save tabs in a bookmark directory. This is really well done :+1:

**Comment by igorlogius** [comment]
Hope it helps and let me know if you find any bugs, so i can fix them. Bye.
