### ISSUE TITLE
Make the "Minimum number of tabs to always keep open" to be zero instead of 1

### ISSUE THREAD

**Issue by joel72265** [igorlogius/auto-close-tabs#6]
**Is your feature request related to a problem? Please describe.**
not related

**Describe the solution you'd like**
to allow the number of "Minimum number of tabs to always keep open" to be zero instead of 1. 

**Describe alternatives you've considered**
None

Update
the unpinned tab (last tab) does not close after the timeout

**Settings Used** (the last tab is unpinned)
Minimum number of tabs to always keep open = 0
Amount of time until a tab is closed = 3

**Comment by igorlogius** [comment]
Done 
ref. https://github.com/igorlogius/auto-close-tabs/commit/775f2891f9f62a51d3265e8f8dabad56756db7cb
