### ISSUE TITLE
Does not Close the last tab

### ISSUE THREAD

**Issue by joel72265** [igorlogius/auto-close-tabs#9]
**Is your feature request related to a problem? Please describe.**
If only 1 tab is open, the last tab is not closed, (if you manually close the last tab, the browser opens a new blank tab)

**Describe the solution you'd like**
The last open tab should be closed

**Describe alternatives you've considered**

**Additional context**

**Comment by igorlogius** [comment]
The last tab is always 'active' ... currently i exclude the active tabs from the cleanupQuery 

i'll see what i can do.

**Comment by joel72265** [comment]
would be great to have the last tab close as an option too :)

**Comment by igorlogius** [comment]
The problem with this request is that there might be "hidden" tabs in a window, which are currently being ignored (addons like Simple Tab Groups and Tree Style Tabs use this for example ... and if we close the last visible tab ... i think the window will get closed, which might cause unexpected datalose. ... That was the inital reason why i never wanted to close the last tab aka a window.

**Comment by igorlogius** [comment]
Seems like the lastAccessTime for active tabs (aka. last visible tabs in a window) is automatically keeped ... so my current algo can not easily be modified. 

Sorry, but on this basis, i'll have to reject this request.
